'use server';

/**
 * @fileOverview A flow to enhance book descriptions using GenAI.
 *
 * - enhanceBookDescription - A function that enhances a book description.
 * - EnhanceBookDescriptionInput - The input type for the enhanceBookDescription function.
 * - EnhanceBookDescriptionOutput - The return type for the enhanceBookDescription function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const EnhanceBookDescriptionInputSchema = z.object({
  bookDescription: z
    .string()
    .describe('The original book description to be enhanced.'),
});
export type EnhanceBookDescriptionInput = z.infer<
  typeof EnhanceBookDescriptionInputSchema
>;

const EnhanceBookDescriptionOutputSchema = z.object({
  enhancedDescription: z
    .string()
    .describe('The enhanced book description generated by the AI.'),
});
export type EnhanceBookDescriptionOutput = z.infer<
  typeof EnhanceBookDescriptionOutputSchema
>;

export async function enhanceBookDescription(
  input: EnhanceBookDescriptionInput
): Promise<EnhanceBookDescriptionOutput> {
  return enhanceBookDescriptionFlow(input);
}

const prompt = ai.definePrompt({
  name: 'enhanceBookDescriptionPrompt',
  input: {schema: EnhanceBookDescriptionInputSchema},
  output: {schema: EnhanceBookDescriptionOutputSchema},
  prompt: `You are an expert book editor. Enhance the following book description to make it more engaging and informative.

Original Description: {{{bookDescription}}}`,
});

const enhanceBookDescriptionFlow = ai.defineFlow(
  {
    name: 'enhanceBookDescriptionFlow',
    inputSchema: EnhanceBookDescriptionInputSchema,
    outputSchema: EnhanceBookDescriptionOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
